-- TODO gdy reservation.payment_date not null - nie można dorezerwowywać do tej rezerwacji
-- TODO sprawdzać czy conference_attendees_students.conference_attendee_id.conference_reservation_detail_id = student_cards.conference_reservation_detail_id
-- TODO student_cards.count by conference_reservation_detail_id <= conference_reservation_detais.attendeesAmount
-- TODO: workshop_day.(start/stop date) = conference_reservation_details.conference_day.date
-- TODO: suma attendees_amount nie może być większa od workshop_days.max_attendees
-- ?TODO? sprawdzenie czy conference_attendee.conference pokrywa się workshop.conference
